// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreatePostInput struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type DeletePostInput struct {
	ID string `json:"id"`
}

type Post struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type UpdatePostInput struct {
	ID      string  `json:"id"`
	Title   *string `json:"title,omitempty"`
	Content *string `json:"content,omitempty"`
}
